version: '1.0'

services:
  persondb:
    container_name: persondb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
  
  reportdb:
    container_name: reportdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin!5
      - POSTGRES_DB=reportdb
    restart: always
    ports:
        - "5432:5432"
volumes:
  postgres_data: