version: "3.8"
services:
  persondb:
    image: mongo
  
  reportdb:
    image: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine

  person.api:
    image: personapi
    build:
      context: .
      dockerfile: backend/PhoneBook/Services/PersonService/src/PersonService.Api/Dockerfile

  report.api:
    image: reportapi
    build:
      context: .
      dockerfile: backend/PhoneBook/Services/ReportsService/src/ReportsService.Api/Dockerfile

  ocelot.api:
    image: ocelotapi
    build:
      context: .
      dockerfile: backend/PhoneBook/ApiGateway/OcelotApi/Dockerfile  
  
  web.client:
    image: web.client
    build:
      context: ./Client
      dockerfile: ./Dockerfile

volumes:
  mongo_data:
  postgres_data: